# Generated by Django 4.1.7 on 2023-04-03 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "default_related_name": "tasks",
                "ordering": ["is_done", "deadline"],
            },
        ),
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="optional",
            new_name="deadline",
        ),
    ]
